config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader
  validates :text, presence: true, unless: :image?
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user).where('id > ?', params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/views/messages/_message.html.haml
.message{data: {id: message.id}}
  .message__upper-info
    .message__upper-info__talker
      = message.user.name
    .message__upper-info__date
      = message.created_at.strftime("%Y/%m/%d %H:%M:%S")
  .lower-message
    - if message.text.present?
      %p.lower-message__content
        = message.text
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render 'shared/side_bar'

.chat-main
  .main-header
    .main-header__left-box
      - @group.group_users.each do |group_user|
        %h2.main-header__left-box__current-group
          = @group.name
        %ul.main-header__left-box__member-list
          Menber:
          %li.main-header__left-box__member-list__member
          - @group.users.each do |user|
            = user.name
      .main-header__edit-btn
        = link_to "Edit", edit_group_path(@group.id), class: "btn"

  .main-contents
    .messages
      = render @messages

  .form
    = form_for [@group, @message] do |f|
      .input-box
        = f.text_field :text, class: 'input-box__message', placeholder: 'type a message'
        = f.label :image, class: 'input-box__image' do
          = fa_icon 'picture-o', class: 'fa fa-image'
          = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'submit-btn'

app/views/messages/temporary.html.haml
%body
  .flash-box
  .wrapper
    .chat-side
      .side-header    
        .side-header__box
          %p.side-header__box__user-name
            test-user
          %ul.side-header__box__menu
            %li.side-header__box__menu__new-group
              =link_to "#", class: "side-header__btn" do
                = fa_icon 'edit'
            %li.side-header__box__menu__edit-user
              =link_to "#", class: "side-header__btn" do
                = fa_icon 'cog'
      .groups
        = link_to "#", class: "messages" do
          .group
            %p.group__group-name
              test-group
            %p.group__latest-message
              さようなら
          .group
            %p.group__group-name
              sample-group
            %p.group__latest-message
              hello!
          .group
            %p.group__group-name
              example
            %p.group__latest-message
              まだメッセージはありません

  .chat-main
    .main-header
      .main-header__left-box
        %h2.main-header__left-box__current-group
          test-group
        %ul.main-header__left-box__member-list
          member:
          %li.main-header__left-box__member-list__member
            syuji_yamamoto
      .main-header__edit-btn
        = link_to "#", class: "main-header__btn" do
          Edit
    .messages
      .message
        .message__upper-info
          %p.message__upper-info__talker
            test-user
          %p.message__upper-info__date
            2019/09/08(Sun) 16:51:23
        %p.message__text
          こんにちは！
      .message
        .message__upper-info
          %p.message__upper-info__talker
            test-user
          %p.message__upper-info__date
            2019/09/09(Mon) 04:51:23
        %p.message__text
          さようなら
    
%body